### ISSUE TITLE
Feat: Make a custom favicon and a logo for the app.

### ISSUE THREAD

**Issue by Programmer-Arvind** [devXprite/resumave#13]
Currently the website does not have a favicon and a logo in the navbar.
![image](https://github.com/devXprite/resumave/assets/96773379/12456210-1df6-4dae-ab2e-3ef9da779bcd)
The navbar looks odd without a logo. I will make a logo and add favicon for the title bar. Any suggestions for the logo are welcome. Please assign it to me for GSSoC'24

**Comment by saumyajainnn** [comment]
I would like to work on this issue..please assign it to me

**Comment by Programmer-Arvind** [comment]
> I would like to work on this issue..please assign it to me

I have raised the issue and would like to work on it. Sorry.

**Comment by devxprite** [comment]
> Currently the website does not have a favicon and a logo in the navbar. ![image](https://private-user-images.githubusercontent.com/96773379/334675872-12456210-1df6-4dae-ab2e-3ef9da779bcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDQzNTAsIm5iZiI6MTcxNzYwNDA1MCwicGF0aCI6Ii85Njc3MzM3OS8zMzQ2NzU4NzItMTI0NTYyMTAtMWRmNi00ZGFlLWFiMmUtM2VmOWRhNzc5YmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE2MTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNzE3YWI0Nzk1MTQ2NGI4NTI1MWQ0YTc2ZDliYzNlODRmZTc1NTc1MTQ4MmQ5YTcwYWQ0YjliZWEwOWMyODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oQ8M71DTJK7YlOSvm1comDCP4a4TK-SAXGshAlFYoo4) The navbar looks odd without a logo. I will make a logo and add favicon for the title bar. Any suggestions for the logo are welcome. Please assign it to me for GSSoC'24

Hey @Programmer-Arvind , I've assigned you on this issue. Looking forward to seeing your contributions!

Happy coding!!

**Comment by Programmer-Arvind** [comment]
@devXprite You have not assigned it to me yet. Also please add the gssoc and level labels as I am contributing under GSSoC'24

**Comment by devxprite** [comment]
> @devXprite You have not assigned it to me yet. Also please add the gssoc and level labels as I am contributing under GSSoC'24

assigned :+1:

**Comment by sweta-singh28** [comment]
@devXprite Sir, the issue assigned to Programmer-Arvind last month has had no work done yet, and no pull request has been raised so far. Please assign this issue to me so I can complete it within the next 2 days.

**Comment by devxprite** [comment]
> @devXprite Sir, the issue assigned to Programmer-Arvind last month has had no work done yet, and no pull request has been raised so far. Please assign this issue to me so I can complete it within the next 2 days.

Assigned  👍

**Comment by sweta-singh28** [comment]
@devXprite sir,  please assign a label for the level as it is necessary for getting points in GSSOC.

**Comment by sweta-singh28** [comment]
> @devXprite sir, please assign a label for the level as it is necessary for getting points in GSSOC.

@devXprite sir, please sir assign a label for level so i can start working on it asap.
