### ISSUE TITLE
User should be able to download and preview resume only when its not empty

### ISSUE THREAD

**Issue by Khushalsarode** [devXprite/resumave#21]
Now the resume pdf is downloaded if its totally empty page and also preview even its empty; so want to add state where its will not get downloaded if empty and not preview of empty page too.

**Comment by devxprite** [comment]
> Now the resume pdf is downloaded if its totally empty page and also preview even its empty; so want to add state where its will not get downloaded if empty and not preview of empty page too.

Thanks for raising this issue! Would you be interested in working on it? Let us know if you're up for it!

**Comment by Khushalsarode** [comment]
Sure, I'm up for it! If you will assign it to me

**Comment by Khushalsarode** [comment]
Can you add labels?

**Comment by Khushalsarode** [comment]
Now the resume can't be previewed or downloaded, Till the movement user doesn't fill required information including experience section.

![Screenshot 2024-06-09 015331](https://github.com/devXprite/resumave/assets/105520366/bc48a6a5-c2b9-408b-9e8e-05ba35c12ab7)

**Comment by Monik2002** [comment]
What about a fresher who has no experience ?

**Comment by Khushalsarode** [comment]
> What about a fresher who has no experience ?

Then simply fill the project section!
