### ISSUE TITLE
add sign up and login 

### ISSUE THREAD

**Issue by ranjaniav1** [devXprite/resumave#5]
Hey @devXprite ,
add sign up and login pages with functionality for authentication:
![image](https://github.com/devXprite/resumave/assets/137641079/8c36493b-6f22-41da-901c-54fcc2584233)
![image](https://github.com/devXprite/resumave/assets/137641079/a184f29a-e982-4167-9543-513d9379d4dc)
![image](https://github.com/devXprite/resumave/assets/137641079/df2c2935-e659-49d0-826d-2dba9a93919f)

**Comment by vansh-sardana** [comment]
Hi @devXprite, I would like to work on this issue. Kindly assign this to me.

**Comment by Tanishka023** [comment]
Hey!! I am excited to contribute to this project, please assign this to me @Varsani2520 @vansh-sardana

**Comment by shashbh18** [comment]
Please assign this to me.I would love to work on this.

**Comment by devxprite** [comment]
> Hey @devXprite , add sign up and login pages with functionality for authentication: ![image](https://private-user-images.githubusercontent.com/137641079/333987894-8c36493b-6f22-41da-901c-54fcc2584233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDMxMDgsIm5iZiI6MTcxNzYwMjgwOCwicGF0aCI6Ii8xMzc2NDEwNzkvMzMzOTg3ODk0LThjMzY0OTNiLTZmMjItNDFkYS05MDFjLTU0ZmNjMjU4NDIzMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxNTUzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTljNDc0MGMzZWYwYTRmZWEzZTE0YTNkZjU5Zjk0N2Q2N2Y3NzM0MDBmNjBjZmRjMWEyNjljYzIxMTA2YjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TfSzUGoz5m3wz4LPJxSXDQQ8-A3vdBUzBBkCBrgWR2E) ![image](https://private-user-images.githubusercontent.com/137641079/333987919-a184f29a-e982-4167-9543-513d9379d4dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDMxMDgsIm5iZiI6MTcxNzYwMjgwOCwicGF0aCI6Ii8xMzc2NDEwNzkvMzMzOTg3OTE5LWExODRmMjlhLWU5ODItNDE2Ny05NTQzLTUxM2Q5Mzc5ZDRkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxNTUzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTVkNzUzMTFkYWJjMjUxNjY3MjQ5ZjZiZjgzODhhODI3N2FjOTQ5ZWUxMzM1OTQ0YWJiOTgxZjZiY2Y4ODNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qQ1qQOKsZlWWFk0N8OhOsr5Lkp2yjhljxlMD3QQB6nY) ![image](https://private-user-images.githubusercontent.com/137641079/333987943-df2c2935-e659-49d0-826d-2dba9a93919f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MDMxMDgsIm5iZiI6MTcxNzYwMjgwOCwicGF0aCI6Ii8xMzc2NDEwNzkvMzMzOTg3OTQzLWRmMmMyOTM1LWU2NTktNDlkMC04MjZkLTJkYmE5YTkzOTE5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxNTUzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWZjMDM1MDk4NDE5ODkyNzVjYWRlNDQ3NGJmY2U4Y2RiNTE1MGMxNWE2YjNlM2I1YjM2NTE2YTA1NGU5MDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e3oDdZuYQHbAwizvgHoUdEXK0wbEc9LSDd1fXk_4nKY)

Thank you for the suggestion but at this time we don't see a need for adding sign-up and login functionality to the project.
